artifact_location: file:///media/aglisman/Linux_Overflow/home/aglisman/VSCodeProjects/OpenADMET-ExpansionRx-Blind-Challenge/None/0
creation_time: 1766007257086
experiment_id: '0'
last_update_time: 1766007257086
lifecycle_stage: active
name: Default
